### ISSUE TITLE
Dashboard Preview - Min Window width Bug

### ISSUE THREAD

**Issue by jkmarx** [refinery-platform/refinery-platform#1461]
Specific code commit: e483ddf
Version of the web browser and OS: Chrome 53.0, Mac 10.11.4
Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org/
### Steps to reproduce

Please list all the actions and the input data used:
1. On the dashboard, adjust width to < 970px
2. Open preview
### Observed behavior

Can not scroll over to see preview also it is not stacked below (when not in preview the analyses and workflow panels are stacked below)
### Expected behavior

To be able to scroll over and see the preview

**Comment by mccalluc** [comment]
Screen shot to demonstrate the problem:
<img width="678" alt="screen shot 2016-10-11 at 1 12 53 pm" src="https://cloud.githubusercontent.com/assets/730388/19280577/94d4bd0c-8fb4-11e6-8a15-736bed485699.png">

Below that width, to be responsive the divs take up the whole width. If you're looking into the responsiveness of this page also note that the top of the content is also being hidden by the header: it can not be scrolled up any higher.

I'm also not sure what the solution is: While it's true that without the preview, the three panes are stacked one on top of the other and you could scroll to the lower ones, in practice, many users will not discover that: almost all of the page is consumed with the scrollable list, so if you're just scrolling with the trackpad, you're likely to scroll that pane rather than the actual window.

**Comment by mccalluc** [comment]
With more headers on the beta site ("Collaboration    Statistics    About    Original Site    CSCB Home") it's easier to hit this. 

For some widths, it also exactly obscures the "Registration for full access..." note, and it's not obvious that anything is missing.

**Comment by mccalluc** [comment]
(Image also demonstrates #1876: header wrap obscuring top of content.)

**Comment by jkmarx** [comment]
Given the dashboard redesign in the next two milestones, closing this issue.
