### ISSUE TITLE
Revise indexing of data sets in Refinery

### ISSUE THREAD

**Issue by sjhosui** [refinery-platform/refinery-platform#1702]
Index on the following fields:
- [x] Study Person Last Name (i.e. PI)
    - The information has always been indexed but the last name could not be retrieved properly. For example, one could search for `Ramesh` but not `Shivdasani` before PR #1716 
- [x] Study Assay Measurement Type (i.e. technology type)
- [x] Study Identifier 
- [x] External ID (GSE)
- [x] index Description as an `EdgeNGram` field and test performance
 - [x] Are we indexing on both the title and description? **YES, see: https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/core/search_indexes.py#L22-L37**

- [x] Look into this error:
`2017-05-03 15:24:56 ERROR    core.utils:54 update_data_set_index() - Could not update DataSetIndex: 'module' object has no attribute 'search_indexes'`

**Comment by scottx611x** [comment]
@sjhosui @ngehlenborg 

I'm not seeing the `Study Person Last Name (i.e. PI)` information within a DataSet of any of its associated models. Is this something contained in the ISATAB standard that we aren't pulling out?

It's also not clear to me what a `Study Identifier` or `External ID` are in this context.

I think the real issue is that indexing may just be broken ( RE: `2017-05-03 15:24:56 ERROR core.utils:54 update_data_set_index() - Could not update DataSetIndex: 'module' object has no attribute 'search_indexes'`)

If dataset indexing has been broken for awhile this could explain many of the issues we've been seeing w/ search.

**Comment by scottx611x** [comment]
Addressed by #1716
