### ISSUE TITLE
Search discrepancy: cdx vs. cdx2

### ISSUE THREAD

**Issue by scottx611x** [refinery-platform/refinery-platform#1703]
* Specific code commit: abca28511c9646c389bd13927898d8d40935afa6
* Version of the web browser and OS: `Chrome Version 57.0.2987.133 (64-bit) OS X 10.12`
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
`beta.stemcellcommons.org`

### Steps to reproduce
1. Search for `cdx` in the Dataset search bar:
![screen shot 2017-05-01 at 1 12 34 pm](https://cloud.githubusercontent.com/assets/5629547/25586983/ec6ef80c-2e6f-11e7-8161-cb440f4f836f.png)

2. Search for `cdx2`:
![screen shot 2017-05-01 at 1 12 51 pm](https://cloud.githubusercontent.com/assets/5629547/25586990/f63e7a2e-2e6f-11e7-9ee5-ada24700e778.png)

### Observed behavior
* Searching for `cdx2` yields three more results than `cdx` even though `cdx` is a substring.

### Expected behavior
* `cdx2` results should probably be shown when searching for `cdx`
* The current observance could be the expected behavior if the search relies on a lazy matching approach?

**Comment by flekschas** [comment]
As far as I remember there is no prefix search across the data set description as the description can potentially be very long and prefix search can be slow (and resource intensive). The extra search results for `cdx2` are coming from exact matches in the description (that's why searching for `cdx` does not highlight `cdx2` in the data set description).
You can change that behavior by adjusting the way the data set description in stored in Solr. Title is a Edge n-gram field while the description is just a text field if I remember correctly.

**Comment by scottx611x** [comment]
@flekschas Awesome, thanks for the quick response 🎊

**Comment by scottx611x** [comment]
Related to #1702

**Comment by scottx611x** [comment]
Addressed by #1702
