### ISSUE TITLE
File not found error for /static/images/icons.svg

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#1967]
* Specific code commit: release v1.5.8
* Version of the web browser and OS: any
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): AWS

### Steps to reproduce
Load the launchpad in a web browser

### Observed behavior
Error message in the browser console:
```
Failed to load resource: the server responded with a status of 404 (NOT FOUND) /static/images/icons.svg#cursor-default
```

### Expected behavior
No errors in the console.

**Comment by mccalluc** [comment]
I think these are the places that need to be fixed? I'm not confident that plugging in `this.$window.getStaticUrl()` is trivial, or maybe there's a different fix?
```
$ git grep -n icons.svg | grep -v getStaticUrl | perl -npe 's{refinery/ui/}{};s/\s+/ /'
config.json:61: "d3-list-graph/dist/icons.svg"
source/js/commons/treemap/template.html:53: xlink:href="/static/images/icons.svg#maximize"></use>
source/js/commons/treemap/template.html:70: xlink:href="/static/images/icons.svg#equalize"></use>
source/js/commons/treemap/template.html:87: xlink:href="/static/images/icons.svg#minimize"></use>
source/js/dashboard/services/intros/satori-list-graph.js:91: '    xlink:href="/static/vendor/d3-list-graph/dist/icons.svg#' + name + '">' +
source/js/dashboard/views/launch-pad.html:33: xlink:href="/static/images/icons.svg#cursor-default"></use>
source/js/dashboard/views/launch-pad.html:48: xlink:href="/static/images/icons.svg#cursor-click"></use>
source/js/dashboard/views/launch-pad.html:64: xlink:href="/static/images/icons.svg#cursor-click"></use>
source/js/dashboard/views/launch-pad.html:77: xlink:href="/static/images/icons.svg#cursor-dblclick"></use>
```

**Comment by hackdna** [comment]
[Some examples](https://github.com/refinery-platform/refinery-platform/commit/1a6e95849217a795adbf5618b884358cc6243416#diff-725225ba648903bddb46828a4cbf0ea1)

**Comment by mccalluc** [comment]
I believe this is the same as #1905. In that thread, Fritz does not believe that adding `getStaticUrl()` is the best way to address this. Closing as duplicate.

**Comment by scottx611x** [comment]
Not a dup of #1905

**Comment by scottx611x** [comment]
To alleviate any confusion in the future:
#1905 led to a lot of discussion as to how to get the Satori svg icons to show up. We couldn't come to a unanimous agreement and `v1.5.8` was in need of deployment with these icons loading properly so  we introduced a 3rd party package as a quick fix called: `svgxuse`. 

In short, `svgxuse` will fetch and load svgs even if we run into `(blocked:origin)` errors. But these errors will still show up in the console.
See below (`icons.svg` url: https://refinery-all-files-test-static.s3.amazonaws.com/images/icons.svg):
![screen shot 2017-09-06 at 3 53 49 pm](https://user-images.githubusercontent.com/5629547/30131672-a081cdbe-931b-11e7-9fac-5a27b72922f5.png)

This issue seems to be different as we are actually getting 404s not `(blocked:origin)`.
`svgxuse` will try to fetch again, but still 404.
See below (`icons.svg` url: https://test.stemcellcommons.org/static/images/icons.svg)
![screen shot 2017-09-06 at 3 53 20 pm](https://user-images.githubusercontent.com/5629547/30131698-b742bd74-931b-11e7-9f31-47f7906df93f.png)

The 404 seems to be coming from this file: https://github.com/refinery-platform/refinery-platform/blob/develop/refinery/ui/source/images/icons.svg
