### ISSUE TITLE
Add data files to an existing data set

### ISSUE THREAD

**Issue by drj11** [refinery-platform/refinery-platform#2037]
From the Jamboree document, which says: "Revising previously uploaded data sets by matching uploaded files to file references that still exist in the data set".

**Comment by gmnelson** [comment]
I believe the issue here relates to when a user uploads a data set (both metadata and files) and then, at a later time, wants to add some more files to that data set. Currently this is accomplished by repeating the data set upload process (keeping the same data set name), which requires uploading both the existing files (again) and new files.

It would be better if, during this second upload procedure, any previously uploaded files specified in the metadata were automatically associated with the newer, revised data set without the need for re-upload. This would mean that, when revising data sets, the only files that need to be uploaded are those new files that the user wants to add.

**Comment by drj11** [comment]
Oh I did not know you could do that.

**Comment by jkmarx** [comment]
@scottx611x Duplicate?
