### ISSUE TITLE
Allow associating uploaded data files with data sets imported from ISA archives

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#2053]
Currently, ISA archives must reference data files by URLs for successful import into Refinery. We need to allow uploading data files during ISA archive import and associating these data files with the resulting data set.

This requires:
* adding file upload functionality to the ISA-Tab import form (POSIX file system upload on Vagrant and S3 upload on AWS)
* changing ISA archive import process to allow adding files from the upload area on S3 (AWS) or from the data file import directory (Vagrant)

Technical debt:
refactor `parse_isatab()` to return data set UUID only (other return items are not actually used)

**Comment by scottx611x** [comment]
@hackdna I have a suspicion that this will break the current `Import into own space` functionality. Not 100% sure, but might be good to keep in mind

**Comment by hackdna** [comment]
Which part of that (specific code) would be vulnerable do you think?

**Comment by scottx611x** [comment]
So the `Import into own space` feature utilizes `TakeOwnershipOfPublicDatasetView` which then talks to `ProcessISATabView`. Since we are only dealing with ISA-Tab metadata urls atm we would presumably need to gather and reassociate the necessary datafiles that a user could now associate with the initial ISA-Tab and associate them with the metadata file that we reimport. (I haven't seen your code from the hackathon, but I'd be glad to help when this is being implemented. Also I don't think there are any tests for `Import into own space` so that should be done as well (shame on me!))

**Comment by hackdna** [comment]
This requires a rewrite of `TakeOwnershipOfPublicDatasetView` to perform a deep copy of the imported data set instead of re-importing the original ISA archive since:
* the ISA archive only has references to the uploaded file names and not the imported files
* `ProcessISATabView` doesn't and shouldn't care about the context of the ISA archive import (regular import vs taking ownership)

In addition, `TakeOwnershipOfPublicDatasetView` is missing support for data sets imported from tabular files.

So, I'm going to submit a pull request covering the original spec for allowing file uploads with ISA archive imports and create a separate issue for updates to `TakeOwnershipOfPublicDatasetView`.
