### ISSUE TITLE
Cross-dataset browser: genotype facets max out at 100?

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/refinery-platform#2148]
* Specific code commit: 2a3c825183c423d388c391f52a18e13d5caa2925
* Version of the web browser and OS: ff macos
* Environment where the error occurred: test production

### Steps to reproduce

https://test.stemcellcommons.org/files/

Looks at the genotype facets.

### Observed behavior
* Only 100 values are given ... probably a limit in solr ... but if we did bump the limit up, would that even be usable?
![screen shot 2017-09-14 at 12 03 04 pm](https://user-images.githubusercontent.com/730388/30440359-43586ef2-9944-11e7-914b-d6c160903f86.png)

**Comment by jkmarx** [comment]
@jkmarx Discuss with @gmnelson

**Comment by jkmarx** [comment]
@sjhosui

**Comment by gmnelson** [comment]
@jkmarx If there is a limit, it must now be > 100:

![image](https://user-images.githubusercontent.com/23487494/36554293-ddf08506-17cc-11e8-8329-a7fcd3036bda.png)

I would say list as many facets as exist for an attribute, particularly since we offer sorting by counts and searching by keyword.

In fact, in case a limit does still exist, does that mean that facets that are not shown are also not accessible by keyword search? If this would be the case, I would argue even more strongly for showing everything.

**Comment by jkmarx** [comment]
I'm closing, there doesn't appear to be a limit. 
<img width="195" alt="screen shot 2018-07-24 at 10 32 45 am" src="https://user-images.githubusercontent.com/9956764/43145244-f25c5d76-8f2c-11e8-9324-7c086ca1e3c0.png">
