### ISSUE TITLE
Add error handling for code that's retrieving model instances.

### ISSUE THREAD

**Issue by hackdna** [refinery-platform/refinery-platform#281]
for example:

analysis_status = AnalysisStatus.objects.get(analysis=analysis)
could raise DoesNotExist or MultipleObjectsReturned exceptions

analysis = Analysis.objects.filter(uuid=analysis.uuid)[0]
could raise IndexError exception

Pivotal Tracker story 52548673 (Ilya Sytchev - Jun 28, 2013)

**Comment by ngehlenborg** [comment]
Any idea how to find all those instances to address this comprehensively?

**Comment by hackdna** [comment]
A decorator might work.

**Comment by scottx611x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;u3beoNzc&#x2F;4-281"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #281</a>

**Comment by ilan-gold** [comment]
@jkmarx should i look at the annotation server given #3329 ?

**Comment by jkmarx** [comment]
Skipping it makes sense.

**Comment by ngehlenborg** [comment]
We should ultimately remove that app.

On Aug 29, 2019, at 1:46 PM, Jennifer Marx <notifications@github.com<mailto:notifications@github.com>> wrote:


Skipping it makes sense.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_refinery-2Dplatform_refinery-2Dplatform_issues_281-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAJJABUF7WRZM5LC76D7PCDQHADQRA5CNFSM4AMGZFBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5PI7SQ-23issuecomment-2D526290890&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=WqvMcWma-3T-cU3UhR-U6CbL7lVAd7UynRU_FgPxleM&s=GRKT64MSOkRdrcvJDeNN7P-gcXshkXrgiin9MZgYMDo&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAJJABXD3XB7IVSFYJCMFIDQHADQRANCNFSM4AMGZFBA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=-zahbihG7P2H0fiPo3RTqce9mFyFku-NJy5aRYNyUSA&m=WqvMcWma-3T-cU3UhR-U6CbL7lVAd7UynRU_FgPxleM&s=7WGjwVEa2MCe4XD2Lwsjjj8AHBBMS_rNAhtTDQTmAjo&e=>.

--
Nils Gehlenborg, PhD
nils@hms.harvard.edu<mailto:nils@hms.harvard.edu> | +1 617-432-1535

Harvard Medical School
Department of Biomedical Informatics

http://gehlenborglab.org
