### ISSUE TITLE
configure Refinery VMs to use https

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#318]
Pivotal Tracker story 43065091 (Nils Gehlenborg - Jan 23, 2013)

**Comment by ngehlenborg** [comment]
@hackdna: is this still necessary?

**Comment by hackdna** [comment]
I'm not sure what is this in reference to exactly. If it's about being able to run the site over HTTPS on Vagrant VM then it's still relevant.

**Comment by hackdna** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xQKYsooz&#x2F;237-add-ssl-functionality-to-aws-stack"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add SSL functionality to AWS stack</a>

**Comment by scottx611x** [comment]
Related to https://github.com/parklab/refinery-platform/issues/1063

**Comment by scottx611x** [comment]
#### Evaluating options for `http` or `https` usage:

**These both require an `HttpRequest` object, whereas we are currently dealing with `relative_url`s as strings**
- https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.build_absolute_uri 
- https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.is_secure

**These may be good for the future when a Refinery Instance utilizing HTTPS is available to test them out on**
- https://docs.python.org/2/library/wsgiref.html#wsgiref.util.guess_scheme
- http://wsgi.readthedocs.io/en/latest/definitions.html#envvar-wsgi.url_scheme
- https://www.python.org/dev/peps/pep-0333/#url-reconstruction

**This way is simple enough and it make it clear as to/easy to find what protocol we are using since this change exists with all of our other settings**
- https://fragmentsofcode.wordpress.com/2009/02/24/django-fully-qualified-url/

I've currently implemented the last item in the list to take care of construction of our full urls, but the middle 3 links will help out later on.

Once an instance using HTTPS is available to test on, it looks pretty straightforward to implement some of the more robust solutions.

**Comment by hackdna** [comment]
Already implemented.

**Comment by scottx611x** [comment]
@hackdna How do we do this? Is there documentation somewhere?

**Comment by hackdna** [comment]
[ELB config](https://github.com/refinery-platform/refinery-platform/blob/d87a66fcc375d6cd9d95d47bf2465c9f175544b7/deployment/stack.py#L474) and [Apache config](https://github.com/refinery-platform/refinery-platform/blob/d87a66fcc375d6cd9d95d47bf2465c9f175544b7/deployment/refinery-modules/refinery/manifests/apache2.pp#L43)

**Comment by scottx611x** [comment]
@hackdna Okay, but I think this issue is just for running behind https in Vagrant, which is not clear to me how we would do at the moment.

**Comment by hackdna** [comment]
OK. I don't think using HTTPS in Vagrant is actually useful since it is an insecure development environment by definition (and implementation would be significantly different from AWS anyway, so not useful for testing of HTTPS either).
