### ISSUE TITLE
investigate options to integrate Web Sockets into Refinery

### ISSUE THREAD

**Issue by ngehlenborg** [refinery-platform/refinery-platform#707]
Can we get information about options from the Caleydo Web docs?

**Comment by flekschas** [comment]
[WAMP][http://wamp.ws/] protocols builds on top of web sockets and has great implementations:
- [Autobahn][http://autobahn.ws/]
- [Crossbar.io][http://crossbar.io/]
- http://tavendo.com/blog/post/is-crossbar-the-future-of-python-web-apps/

ReactiveX design pattern sounds interesting as it combines event handling, REST queries, web socket and so on:
- [rx-book][https://xgrommx.github.io/rx-book/index.html]
- [RXJS][https://github.com/Reactive-Extensions/RxJS]
- [RXPY][https://github.com/ReactiveX/RxPY]

(will keep on updating)

**Comment by ngehlenborg** [comment]
What about http://tornado.readthedocs.org/en/latest/index.html? 

Did you find any examples for Autobahn.ws/Crossbar.io Django?

**Comment by ngehlenborg** [comment]
Also see here: http://epiviz.github.io/websocket.html

**Comment by hackdna** [comment]
[Server-Sent Events vs. WebSockets](http://www.html5rocks.com/en/tutorials/eventsource/basics/):
* WebSockets provide a richer protocol to perform bi-directional, full-duplex communication.
* In some scenarios data doesn't need to be sent from the client. You simply need updates from some server action.
* SSEs are sent over traditional HTTP. That means they do not require a special protocol or server implementation to get working.
* WebSockets on the other hand, require full-duplex connections and new Web Socket servers to handle the protocol.
* Server-Sent Events have a variety of features that WebSockets lack by design such as automatic reconnection, event IDs, and the ability to send arbitrary events.

**Comment by flekschas** [comment]
One thing to keep in mind about SSE:

> Websockets and SSE (Server Sent Events) are both capable of pushing data to browsers, however they are not competing technologies.
> Websockets connections can both send data to the browser and receive data from the browser. A good example of an application that could use websockets is a chat application.
> SSE connections can only push data to the browser. Online stock quotes, or twitters updating timeline or feed are good examples of an application that could benefit from SSE.

http://stackoverflow.com/a/5326159/981933

**Comment by hackdna** [comment]
Django was funded to rewrite the core to support WebSockets: https://www.djangoproject.com/weblog/2015/dec/11/django-awarded-moss-grant/

**Comment by flekschas** [comment]
Great! Unfortunately not a short term solution:

> There's no exact timeline for the project yet, but keep an eye on the django-developers mailing list for updates as work progresses.

**Comment by ngehlenborg** [comment]
We can bring this up later, currently not relevant.
