### ISSUE TITLE
Locking a node in the treemap doesn't highlight it in the list graph

### ISSUE THREAD

**Issue by flekschas** [refinery-platform/refinery-platform#954]
For some reasons all indirectly locked nodes are highlighted but the directly locked nodes is not colored orange.

**Comment by mccalluc** [comment]
@flekschas : Unless I'm misunderstanding, this does not seem to be a problem any longer. "Direct" and "indirect" means parent and child? Those nodes in the list graph are being highlighted, and that's the expected behavior. Will close, but reopen if I'm missing the point.

<img width="810" alt="screen shot 2017-07-18 at 4 27 20 pm" src="https://user-images.githubusercontent.com/730388/28338197-2ec6cf9c-6bd6-11e7-9c23-6bd0fd3f9363.png">

**Comment by flekschas** [comment]
Yes all good. Ontologies are poly hierarchies that's why you can sometimes see funky looking stuff
